# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QSizePolicy, QSplitter, QVBoxLayout,
    QWidget)

class Ui_Program(object):
    def setupUi(self, Program):
        if not Program.objectName():
            Program.setObjectName(u"Program")
        Program.setWindowModality(Qt.WindowModal)
        Program.resize(794, 587)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Program.sizePolicy().hasHeightForWidth())
        Program.setSizePolicy(sizePolicy)
        Program.setSizeIncrement(QSize(591, 487))
        Program.setWindowFlags(Qt.WindowCloseButtonHint | Qt.WindowMinimizeButtonHint)
        Program.setMaximumSize(794, 587)
        icon = QIcon()
        icon.addFile(u"/etc/debpackagebuilder/icon.png", QSize(), QIcon.Normal, QIcon.Off)
        Program.setWindowIcon(icon)
        Program.setLayoutDirection(Qt.LeftToRight)
        Program.setAutoFillBackground(False)
        self.btnCompile = QPushButton(Program)
        self.btnCompile.setObjectName(u"btnCompile")
        self.btnCompile.setEnabled(False)
        self.btnCompile.setGeometry(QRect(630, 540, 151, 31))
        self.horizontalLayoutWidget_5 = QWidget(Program)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(10, 10, 771, 251))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.groupBox = QGroupBox(self.horizontalLayoutWidget_5)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        self.horizontalLayoutWidget = QWidget(self.groupBox)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 30, 131, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")

        self.horizontalLayout.addWidget(self.label)

        self.verticalLayoutWidget = QWidget(self.groupBox)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(150, 30, 601, 41))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.txtPackagename = QLineEdit(self.verticalLayoutWidget)
        self.txtPackagename.setObjectName(u"txtPackagename")
        self.txtPackagename.setMaxLength(50)
        self.verticalLayout.addWidget(self.txtPackagename)

        self.verticalLayoutWidget_2 = QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(150, 70, 601, 41))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.txtDesc = QLineEdit(self.verticalLayoutWidget_2)
        self.txtDesc.setObjectName(u"txtDesc")

        self.verticalLayout_5.addWidget(self.txtDesc)

        self.horizontalLayoutWidget_2 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(10, 70, 131, 41))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout_2.addWidget(self.label_2)

        self.verticalLayoutWidget_3 = QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(150, 110, 321, 41))
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.txtMaintainer = QLineEdit(self.verticalLayoutWidget_3)
        self.txtMaintainer.setObjectName(u"txtMaintainer")

        self.verticalLayout_6.addWidget(self.txtMaintainer)

        self.horizontalLayoutWidget_3 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 110, 131, 41))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout_3.addWidget(self.label_3)

        self.horizontalLayoutWidget_4 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(530, 110, 101, 41))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout_4.addWidget(self.label_4)

        self.verticalLayoutWidget_4 = QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(630, 110, 121, 41))
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.txtVersion = QLineEdit(self.verticalLayoutWidget_4)
        self.txtVersion.setObjectName(u"txtVersion")

        self.verticalLayout_7.addWidget(self.txtVersion)

        self.splitter = QSplitter(self.groupBox)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(20, 40, 0, 25))
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter_2 = QSplitter(self.splitter)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.splitter.addWidget(self.splitter_2)
        self.horizontalLayoutWidget_13 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_13.setObjectName(u"horizontalLayoutWidget_13")
        self.horizontalLayoutWidget_13.setGeometry(QRect(10, 150, 131, 41))
        self.horizontalLayout_13 = QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.horizontalLayoutWidget_13)
        self.label_7.setObjectName(u"label_7")

        self.horizontalLayout_13.addWidget(self.label_7)

        self.verticalLayoutWidget_6 = QWidget(self.groupBox)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(150, 150, 321, 41))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.txtDepends = QLineEdit(self.verticalLayoutWidget_6)
        self.txtDepends.setObjectName(u"txtDepends")

        self.verticalLayout_3.addWidget(self.txtDepends)

        self.horizontalLayoutWidget_14 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_14.setObjectName(u"horizontalLayoutWidget_14")
        self.horizontalLayoutWidget_14.setGeometry(QRect(10, 190, 131, 41))
        self.horizontalLayout_14 = QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.horizontalLayoutWidget_14)
        self.label_8.setObjectName(u"label_8")

        self.horizontalLayout_14.addWidget(self.label_8)

        self.verticalLayoutWidget_7 = QWidget(self.groupBox)
        self.verticalLayoutWidget_7.setObjectName(u"verticalLayoutWidget_7")
        self.verticalLayoutWidget_7.setGeometry(QRect(150, 190, 161, 51))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.cbOpenInTerminal = QCheckBox(self.verticalLayoutWidget_7)
        self.cbOpenInTerminal.setObjectName(u"cbOpenInTerminal")

        self.verticalLayout_4.addWidget(self.cbOpenInTerminal)

        self.verticalLayoutWidget_8 = QWidget(self.groupBox)
        self.verticalLayoutWidget_8.setObjectName(u"verticalLayoutWidget_8")
        self.verticalLayoutWidget_8.setGeometry(QRect(310, 190, 164, 51))
        self.verticalLayout_8 = QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.cbShowNotify = QCheckBox(self.verticalLayoutWidget_8)
        self.cbShowNotify.setObjectName(u"cbShowNotify")

        self.verticalLayout_8.addWidget(self.cbShowNotify)

        self.verticalLayoutWidget_9 = QWidget(self.groupBox)
        self.verticalLayoutWidget_9.setObjectName(u"verticalLayoutWidget_9")
        self.verticalLayoutWidget_9.setGeometry(QRect(630, 190, 121, 51))
        self.verticalLayout_9 = QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.cbxArchitecture = QComboBox(self.verticalLayoutWidget_9)
        self.cbxArchitecture.setObjectName(u"cbxArchitecture")

        self.verticalLayout_9.addWidget(self.cbxArchitecture)

        self.verticalLayoutWidget_10 = QWidget(self.groupBox)
        self.verticalLayoutWidget_10.setObjectName(u"verticalLayoutWidget_10")
        self.verticalLayoutWidget_10.setGeometry(QRect(530, 190, 101, 51))
        self.verticalLayout_10 = QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.verticalLayoutWidget_10)
        self.label_12.setObjectName(u"label_12")

        self.verticalLayout_10.addWidget(self.label_12)

        self.verticalLayoutWidget_11 = QWidget(self.groupBox)
        self.verticalLayoutWidget_11.setObjectName(u"verticalLayoutWidget_11")
        self.verticalLayoutWidget_11.setGeometry(QRect(530, 150, 101, 41))
        self.verticalLayout_11 = QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_13 = QLabel(self.verticalLayoutWidget_11)
        self.label_13.setObjectName(u"label_13")

        self.verticalLayout_11.addWidget(self.label_13)

        self.verticalLayoutWidget_12 = QWidget(self.groupBox)
        self.verticalLayoutWidget_12.setObjectName(u"verticalLayoutWidget_12")
        self.verticalLayoutWidget_12.setGeometry(QRect(630, 150, 121, 41))
        self.verticalLayout_12 = QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.cbxCategory = QComboBox(self.verticalLayoutWidget_12)
        self.cbxCategory.setObjectName(u"cbxCategory")

        self.verticalLayout_12.addWidget(self.cbxCategory)


        self.horizontalLayout_5.addWidget(self.groupBox)

        self.horizontalLayoutWidget_6 = QWidget(Program)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(460, 440, 321, 91))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.txtResult = QPlainTextEdit(self.horizontalLayoutWidget_6)
        self.txtResult.setObjectName(u"txtResult")
        font = QFont()
        font.setFamilies([u"DejaVu Sans"])
        font.setPointSize(7)
        self.txtResult.setFont(font)
        self.txtResult.setReadOnly(True)

        self.horizontalLayout_6.addWidget(self.txtResult)

        self.horizontalLayoutWidget_7 = QWidget(Program)
        self.horizontalLayoutWidget_7.setObjectName(u"horizontalLayoutWidget_7")
        self.horizontalLayoutWidget_7.setGeometry(QRect(20, 320, 131, 41))
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.horizontalLayoutWidget_7)
        self.label_5.setObjectName(u"label_5")

        self.horizontalLayout_7.addWidget(self.label_5)

        self.horizontalLayoutWidget_8 = QWidget(Program)
        self.horizontalLayoutWidget_8.setObjectName(u"horizontalLayoutWidget_8")
        self.horizontalLayoutWidget_8.setGeometry(QRect(160, 320, 531, 41))
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.txtIconFile = QLineEdit(self.horizontalLayoutWidget_8)
        self.txtIconFile.setObjectName(u"txtIconFile")
        self.txtIconFile.setEnabled(True)
        self.txtIconFile.setReadOnly(True)

        self.horizontalLayout_8.addWidget(self.txtIconFile)

        self.horizontalLayoutWidget_9 = QWidget(Program)
        self.horizontalLayoutWidget_9.setObjectName(u"horizontalLayoutWidget_9")
        self.horizontalLayoutWidget_9.setGeometry(QRect(700, 320, 82, 41))
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.btnSearchIcon = QPushButton(self.horizontalLayoutWidget_9)
        self.btnSearchIcon.setObjectName(u"btnSearchIcon")

        self.horizontalLayout_10.addWidget(self.btnSearchIcon)

        self.verticalLayoutWidget_5 = QWidget(Program)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(20, 440, 431, 131))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.txtProjectFiles = QPlainTextEdit(self.verticalLayoutWidget_5)
        self.txtProjectFiles.setObjectName(u"txtProjectFiles")
        self.txtProjectFiles.setFont(font)
        self.txtProjectFiles.setReadOnly(True)

        self.verticalLayout_2.addWidget(self.txtProjectFiles)

        self.horizontalLayoutWidget_10 = QWidget(Program)
        self.horizontalLayoutWidget_10.setObjectName(u"horizontalLayoutWidget_10")
        self.horizontalLayoutWidget_10.setGeometry(QRect(700, 270, 82, 41))
        self.horizontalLayout_11 = QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.btnSearchRootFolder = QPushButton(self.horizontalLayoutWidget_10)
        self.btnSearchRootFolder.setObjectName(u"btnSearchRootFolder")

        self.horizontalLayout_11.addWidget(self.btnSearchRootFolder)

        self.horizontalLayoutWidget_11 = QWidget(Program)
        self.horizontalLayoutWidget_11.setObjectName(u"horizontalLayoutWidget_11")
        self.horizontalLayoutWidget_11.setGeometry(QRect(160, 270, 531, 41))
        self.horizontalLayout_9 = QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.txtRootFolder = QLineEdit(self.horizontalLayoutWidget_11)
        self.txtRootFolder.setObjectName(u"txtRootFolder")
        self.txtRootFolder.setEnabled(True)
        self.txtRootFolder.setReadOnly(True)

        self.horizontalLayout_9.addWidget(self.txtRootFolder)

        self.horizontalLayoutWidget_12 = QWidget(Program)
        self.horizontalLayoutWidget_12.setObjectName(u"horizontalLayoutWidget_12")
        self.horizontalLayoutWidget_12.setGeometry(QRect(20, 270, 131, 41))
        self.horizontalLayout_12 = QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.horizontalLayoutWidget_12)
        self.label_6.setObjectName(u"label_6")

        self.horizontalLayout_12.addWidget(self.label_6)

        self.label_9 = QLabel(Program)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(460, 420, 111, 17))
        self.label_10 = QLabel(Program)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 420, 101, 17))
        self.horizontalLayoutWidget_15 = QWidget(Program)
        self.horizontalLayoutWidget_15.setObjectName(u"horizontalLayoutWidget_15")
        self.horizontalLayoutWidget_15.setGeometry(QRect(700, 370, 82, 41))
        self.horizontalLayout_15 = QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.btnSearchExecutable = QPushButton(self.horizontalLayoutWidget_15)
        self.btnSearchExecutable.setObjectName(u"btnSearchExecutable")

        self.horizontalLayout_15.addWidget(self.btnSearchExecutable)

        self.horizontalLayoutWidget_16 = QWidget(Program)
        self.horizontalLayoutWidget_16.setObjectName(u"horizontalLayoutWidget_16")
        self.horizontalLayoutWidget_16.setGeometry(QRect(20, 370, 131, 41))
        self.horizontalLayout_16 = QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.horizontalLayoutWidget_16)
        self.label_11.setObjectName(u"label_11")

        self.horizontalLayout_16.addWidget(self.label_11)

        self.horizontalLayoutWidget_17 = QWidget(Program)
        self.horizontalLayoutWidget_17.setObjectName(u"horizontalLayoutWidget_17")
        self.horizontalLayoutWidget_17.setGeometry(QRect(160, 370, 531, 41))
        self.horizontalLayout_17 = QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.txtExecutable = QLineEdit(self.horizontalLayoutWidget_17)
        self.txtExecutable.setObjectName(u"txtExecutable")
        self.txtExecutable.setEnabled(True)
        self.txtExecutable.setReadOnly(True)

        self.horizontalLayout_17.addWidget(self.txtExecutable)

        self.btnBuildProject = QPushButton(Program)
        self.btnBuildProject.setObjectName(u"btnBuildProject")
        self.btnBuildProject.setGeometry(QRect(460, 540, 151, 31))
        QWidget.setTabOrder(self.txtPackagename, self.txtDesc)
        QWidget.setTabOrder(self.txtDesc, self.txtMaintainer)
        QWidget.setTabOrder(self.txtMaintainer, self.txtVersion)
        QWidget.setTabOrder(self.txtVersion, self.txtDepends)
        QWidget.setTabOrder(self.txtDepends, self.cbxCategory)
        QWidget.setTabOrder(self.cbxCategory, self.cbOpenInTerminal)
        QWidget.setTabOrder(self.cbOpenInTerminal, self.cbShowNotify)
        QWidget.setTabOrder(self.cbShowNotify, self.cbxArchitecture)
        QWidget.setTabOrder(self.cbxArchitecture, self.txtRootFolder)
        QWidget.setTabOrder(self.txtRootFolder, self.btnSearchRootFolder)
        QWidget.setTabOrder(self.btnSearchRootFolder, self.txtIconFile)
        QWidget.setTabOrder(self.txtIconFile, self.btnSearchIcon)
        QWidget.setTabOrder(self.btnSearchIcon, self.txtExecutable)
        QWidget.setTabOrder(self.txtExecutable, self.btnSearchExecutable)
        QWidget.setTabOrder(self.btnSearchExecutable, self.txtProjectFiles)
        QWidget.setTabOrder(self.txtProjectFiles, self.txtResult)
        QWidget.setTabOrder(self.txtResult, self.btnBuildProject)
        QWidget.setTabOrder(self.btnBuildProject, self.btnCompile)

        self.retranslateUi(Program)

        QMetaObject.connectSlotsByName(Program)
    # setupUi

    def retranslateUi(self, Program):
        Program.setWindowTitle(QCoreApplication.translate("Program", u"Package .deb Creator", None))
        self.btnCompile.setText(QCoreApplication.translate("Program", u"Build .deb file", None))
        self.groupBox.setTitle(QCoreApplication.translate("Program", u"Package Info", None))
        self.label.setText(QCoreApplication.translate("Program", u"(*) Package Name:", None))
        self.txtPackagename.setPlaceholderText(QCoreApplication.translate("Program", u"Ex. mypackagename", None))
        self.txtDesc.setPlaceholderText(QCoreApplication.translate("Program", u"Project description", None))
        self.label_2.setText(QCoreApplication.translate("Program", u"(*) Description:", None))
        self.txtMaintainer.setText("")
        self.txtMaintainer.setPlaceholderText(QCoreApplication.translate("Program", u"Maintainer name", None))
        self.label_3.setText(QCoreApplication.translate("Program", u"(*) Maintainer:", None))
        self.label_4.setText(QCoreApplication.translate("Program", u"(*) Version:", None))
        self.txtVersion.setText(QCoreApplication.translate("Program", u"1.0", None))
        self.txtVersion.setPlaceholderText(QCoreApplication.translate("Program", u"1.0.0.0", None))
        self.label_7.setText(QCoreApplication.translate("Program", u"Depends:", None))
        self.txtDepends.setPlaceholderText(QCoreApplication.translate("Program", u"Ex: libtool libgtk...", None))
        self.label_8.setText(QCoreApplication.translate("Program", u"Options:", None))
        self.cbOpenInTerminal.setText(QCoreApplication.translate("Program", u"Open in Terminal?", None))
        self.cbShowNotify.setText(QCoreApplication.translate("Program", u"Show Install Notify?", None))
        self.label_12.setText(QCoreApplication.translate("Program", u"Architecture:", None))
        self.label_13.setText(QCoreApplication.translate("Program", u"Category:", None))
        self.label_5.setText(QCoreApplication.translate("Program", u"(*) Icon App:", None))
        self.txtIconFile.setPlaceholderText(QCoreApplication.translate("Program", u"PNG, JPG, ICO ...", None))
        self.btnSearchIcon.setText(QCoreApplication.translate("Program", u"Search", None))
        self.btnSearchRootFolder.setText(QCoreApplication.translate("Program", u"Search", None))
        self.txtRootFolder.setPlaceholderText(QCoreApplication.translate("Program", u"select the root folder of your project", None))
        self.label_6.setText(QCoreApplication.translate("Program", u"(*) Root Folder: ", None))
        self.label_9.setText(QCoreApplication.translate("Program", u"Output result:", None))
        self.label_10.setText(QCoreApplication.translate("Program", u"Project Files:", None))
        self.btnSearchExecutable.setText(QCoreApplication.translate("Program", u"Search", None))
        self.label_11.setText(QCoreApplication.translate("Program", u"(*) Executable: ", None))
        self.txtExecutable.setPlaceholderText(QCoreApplication.translate("Program", u"select the executable file for you application", None))
        self.btnBuildProject.setText(QCoreApplication.translate("Program", u"Build Project", None))
    # retranslateUi

